schema_version: 1
site:
  id: cobo-100
  site_code: COBO-100
  city: Cobourg
  province: Ontario
devices:
  firewalls:
  - 3-fw-sonicwall-tz270-cobo-100
  broadcast: []
  servers: []
  network: []
critical_chain: []
notes: ''
